"""Pecah tabel user jadi user, student, teacher

Revision ID: 348d790f1229
Revises: d44e47d7782d
Create Date: 2025-07-06 11:58:14.678567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '348d790f1229'
down_revision: Union[str, Sequence[str], None] = 'd44e47d7782d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('Category_Complete_Sentence',
    # sa.Column('Id_ccs', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.String(length=30), nullable=True),
    # sa.PrimaryKeyConstraint('Id_ccs')
    # )
    # op.create_table('Category_Image_Word',
    # sa.Column('Id_ciw', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.String(length=30), nullable=True),
    # sa.PrimaryKeyConstraint('Id_ciw')
    # )
    # op.create_table('Category_Listening_Sentence',
    # sa.Column('Id_cls', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.String(length=30), nullable=True),
    # sa.PrimaryKeyConstraint('Id_cls')
    # )
    # op.create_table('Category_Listening_Word',
    # sa.Column('Id_clw', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.String(length=30), nullable=True),
    # sa.PrimaryKeyConstraint('Id_clw')
    # )
    # op.create_table('Attempt_Complete_Sentences',
    # sa.Column('Id_attempt', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('score', sa.Float(), nullable=True),
    # sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('Id_category', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['Id_category'], ['Category_Complete_Sentence.Id_ccs'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('Id_attempt')
    # )
    # op.create_table('Attempt_Image_Word',
    # sa.Column('Id_attempt', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('score', sa.Float(), nullable=True),
    # sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('Id_category', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['Id_category'], ['Category_Image_Word.Id_ciw'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('Id_attempt')
    # )
    # op.create_table('Attempt_Listening_Sentence',
    # sa.Column('Id_attempt', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('score', sa.Float(), nullable=True),
    # sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('Id_category', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['Id_category'], ['Category_Listening_Sentence.Id_cls'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('Id_attempt')
    # )
    # op.create_table('Attempt_Listening_Word',
    # sa.Column('Id_attempt', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('score', sa.Float(), nullable=True),
    # sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('Id_category', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['Id_category'], ['Category_Listening_Word.Id_clw'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('Id_attempt')
    # )
    # op.create_table('Complete_Sentence',
    # sa.Column('Id_cs', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('question_cs', sa.String(length=255), nullable=True),
    # sa.Column('cs_answer', sa.String(length=255), nullable=True),
    # sa.Column('Id_ccs', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['Id_ccs'], ['Category_Complete_Sentence.Id_ccs'], ),
    # sa.PrimaryKeyConstraint('Id_cs')
    # )
    # op.create_table('Global_Attempt',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('score', sa.Float(), nullable=True),
    # sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.Column('feature_type', sa.String(length=50), nullable=False),
    # sa.Column('category_id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('Image_Word',
    # sa.Column('Id_iw', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('iw_answer', sa.String(length=30), nullable=True),
    # sa.Column('image_iw', sa.String(length=255), nullable=True),
    # sa.Column('Id_ciw', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['Id_ciw'], ['Category_Image_Word.Id_ciw'], ),
    # sa.PrimaryKeyConstraint('Id_iw')
    # )
    # op.create_table('Listening_Sentence',
    # sa.Column('Id_ls', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('sentence_ls', sa.String(length=100), nullable=True),
    # sa.Column('audio_ls', sa.String(length=255), nullable=True),
    # sa.Column('Id_cls', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['Id_cls'], ['Category_Listening_Sentence.Id_cls'], ),
    # sa.PrimaryKeyConstraint('Id_ls')
    # )
    # op.create_table('Listening_Word',
    # sa.Column('Id_lw', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('lw_answer', sa.String(length=30), nullable=True),
    # sa.Column('audio_lw', sa.String(length=255), nullable=True),
    # sa.Column('Id_clw', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['Id_clw'], ['Category_Listening_Word.Id_clw'], ),
    # sa.PrimaryKeyConstraint('Id_lw')
    # )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('class_name', sa.String(length=10), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_table('Keyword_Listening',
    # sa.Column('Id_keyword', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('keyword_answer', sa.String(length=30), nullable=True),
    # sa.Column('Id_ls', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['Id_ls'], ['Listening_Sentence.Id_ls'], ),
    # sa.PrimaryKeyConstraint('Id_keyword')
    # )
    # op.drop_table('attempt_listening_word')
    # op.drop_table('category_listening_word')
    # op.drop_table('category_listening_sentence')
    # op.drop_table('image_word')
    # op.drop_table('attempt_complete_sentences')
    # op.drop_table('listening_word')
    # op.drop_table('listening_sentence')
    # op.drop_table('attempt_listening_sentence')
    # op.drop_table('category_complete_sentence')
    # op.drop_table('attempt_image_word')
    # op.drop_table('keyword_listening')
    # op.drop_table('category_image_word')
    # op.drop_table('global_attempt')
    # op.drop_table('complete_sentence')
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_nis'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    op.drop_column('users', 'nis')
    op.drop_column('users', 'total_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_score', mysql.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('nis', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_nis'), 'users', ['nis'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'username')
    op.create_table('complete_sentence',
    sa.Column('Id_cs', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('question_cs', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cs_answer', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Id_ccs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Id_ccs'], ['category_complete_sentence.Id_ccs'], name=op.f('complete_sentence_ibfk_1')),
    sa.PrimaryKeyConstraint('Id_cs'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('global_attempt',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.Column('attempted_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('feature_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('global_attempt_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('category_image_word',
    sa.Column('Id_ciw', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('Id_ciw'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('keyword_listening',
    sa.Column('Id_keyword', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('keyword_answer', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Id_ls', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Id_ls'], ['listening_sentence.Id_ls'], name=op.f('keyword_listening_ibfk_1')),
    sa.PrimaryKeyConstraint('Id_keyword'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('attempt_image_word',
    sa.Column('Id_attempt', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.Column('attempted_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Id_category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Id_category'], ['category_image_word.Id_ciw'], name=op.f('attempt_image_word_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attempt_image_word_ibfk_1')),
    sa.PrimaryKeyConstraint('Id_attempt'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('category_complete_sentence',
    sa.Column('Id_ccs', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('Id_ccs'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('attempt_listening_sentence',
    sa.Column('Id_attempt', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.Column('attempted_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Id_category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Id_category'], ['category_listening_sentence.Id_cls'], name=op.f('attempt_listening_sentence_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attempt_listening_sentence_ibfk_1')),
    sa.PrimaryKeyConstraint('Id_attempt'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('listening_sentence',
    sa.Column('Id_ls', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sentence_ls', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('audio_ls', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Id_cls', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Id_cls'], ['category_listening_sentence.Id_cls'], name=op.f('listening_sentence_ibfk_1')),
    sa.PrimaryKeyConstraint('Id_ls'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('listening_word',
    sa.Column('Id_lw', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('lw_answer', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('audio_lw', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Id_clw', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Id_clw'], ['category_listening_word.Id_clw'], name=op.f('listening_word_ibfk_1')),
    sa.PrimaryKeyConstraint('Id_lw'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('attempt_complete_sentences',
    sa.Column('Id_attempt', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.Column('attempted_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Id_category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Id_category'], ['category_complete_sentence.Id_ccs'], name=op.f('attempt_complete_sentences_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attempt_complete_sentences_ibfk_1')),
    sa.PrimaryKeyConstraint('Id_attempt'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('image_word',
    sa.Column('Id_iw', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('iw_answer', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('image_iw', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Id_ciw', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Id_ciw'], ['category_image_word.Id_ciw'], name=op.f('image_word_ibfk_1')),
    sa.PrimaryKeyConstraint('Id_iw'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('category_listening_sentence',
    sa.Column('Id_cls', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('Id_cls'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('category_listening_word',
    sa.Column('Id_clw', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('Id_clw'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('attempt_listening_word',
    sa.Column('Id_attempt', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.Column('attempted_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Id_category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Id_category'], ['category_listening_word.Id_clw'], name=op.f('attempt_listening_word_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attempt_listening_word_ibfk_1')),
    sa.PrimaryKeyConstraint('Id_attempt'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('Keyword_Listening')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('Listening_Word')
    op.drop_table('Listening_Sentence')
    op.drop_table('Image_Word')
    op.drop_table('Global_Attempt')
    op.drop_table('Complete_Sentence')
    op.drop_table('Attempt_Listening_Word')
    op.drop_table('Attempt_Listening_Sentence')
    op.drop_table('Attempt_Image_Word')
    op.drop_table('Attempt_Complete_Sentences')
    op.drop_table('Category_Listening_Word')
    op.drop_table('Category_Listening_Sentence')
    op.drop_table('Category_Image_Word')
    op.drop_table('Category_Complete_Sentence')
    # ### end Alembic commands ###
